import type { Config } from 'tailwindcss';

const config: Config = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'kanto-coral': '#ff8366',
        'kanto-coral-soft': '#fff0eb',
        'kanto-coral-dark': '#ff9a7a',
        'kanto-coral-soft-dark': '#3d1f15',
        'kanto-stall': '#f5ecdc',
        'kanto-stall-dark': '#1f1a14',
        'kanto-stall-edge': '#e8d9bd',
        'kanto-stall-edge-dark': '#332b1f',
        'kanto-tier-new': '#94a3b8',
        'kanto-tier-new-dark': '#64748b',
        'kanto-tier-bronze': '#b45309',
        'kanto-tier-bronze-dark': '#d97706',
        'kanto-tier-silver': '#64748b',
        'kanto-tier-silver-dark': '#94a3b8',
        'kanto-tier-gold': '#ca8a04',
        'kanto-tier-gold-dark': '#eab308',
        'kanto-tier-platinum': '#0e7490',
        'kanto-tier-platinum-dark': '#22d3ee',
        'kanto-bg': '#ffffff',
        'kanto-bg-dark': '#0a0a0a',
        'kanto-surface': '#fafafa',
        'kanto-surface-dark': '#171717',
        'kanto-surface-raised': '#ffffff',
        'kanto-surface-raised-dark': '#262626',
        'kanto-text': '#1a1a1a',
        'kanto-text-dark': '#f5f5f5',
        'kanto-text-soft': '#525252',
        'kanto-text-soft-dark': '#a3a3a3',
        'kanto-text-muted': '#737373',
        'kanto-border': '#e5e5e5',
        'kanto-border-dark': '#404040',
        'kanto-border-strong': '#d4d4d4',
        'kanto-border-strong-dark': '#525252',
        'kanto-teal': '#0d9488',
        'kanto-teal-bright': '#14b8a6',
        'kanto-teal-soft': '#ccfbf1',
        'kanto-teal-dark': '#2dd4bf',
        'kanto-teal-soft-dark': '#134e4a',
      },
      borderRadius: {
        sm: '8px',
        md: '12px',
        lg: '20px',
        xl: '28px',
        pill: '9999px',
      },
      boxShadow: {
        card: '0 8px 24px -6px rgb(0 0 0 / 0.08)',
        'card-hover': '0 16px 40px -8px rgb(0 0 0 / 0.16)',
      },
      fontFamily: {
        sans: ['Inter', 'Cairo', 'system-ui', 'sans-serif'],
        display: ['Orbitron', 'Cairo', 'system-ui', 'sans-serif'],
      },
    },
  },
  plugins: [],
};

export default config;
